services:
  # --- API ---
  api:
    build: .
    container_name: petr4-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      # Mapeia a pasta models (modelos treinados)
      - ./models:/app/models
    restart: always

  # --- MONITORAMENTO (Banco de Dados de Métricas) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: petr4-prometheus
    volumes:
      # Configuração
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # PERSISTÊNCIA
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - api

  # --- VISUALIZAÇÃO (Dashboards) ---
  grafana:
    image: grafana/grafana:latest
    container_name: petr4-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      # PERSISTÊNCIA: gráficos
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

# "HDs Virtuais" do Docker
volumes:
  prometheus_data:
  grafana_data:
