global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'petr4_api'
    static_configs:
      # 'api' é o nome do serviço que definiremos no docker-compose
      # 8000 é a porta interna da API
      - targets: ['api:8000']
